MONGO_DB_ITERATIONS = 100
ELASTICSEARCH_PAGE_SIZE = 100
MONGO_DB_COLLECTION_BULK = False
MONGO_DB_ONLINE = True
MONGO_DB_COLLECTION_OVERRIDE = False


DYNAMO_DB_ONLINE = True
DYNAMODB_COLLECTION_OVERRIDE = True
DYNAMODB_COLLECTION_BULK = True
